# -*- coding: utf-8 -*-
"""Hw2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Wj67M41734qZkUmlL3rEE9McgLkeaDYp
"""

count = 0
stick=int(input("How many sticks in the pile?  "))
print("There are", stick, "sticks in the pile.")
name=input("What is your name?  ")
while stick>0:
  z=int(input(name+", how many sticks you will take(1 or 2)."))
  if (z>0) and (z <= 2):
    if stick<z:
      print("there are not enough sticks to take.")
    else: 
      stick = stick-z
      count +=1
      if stick ==0:
        print("OK. There is no stick left in the pile. You spent ",count," times.") 
      else:
        print("There are",stick,"sticks in the pile.")
    
  elif z > 2:
    print("No! you cannot take more than 2 sticks.")
  else:
    print("No! you can't take less than 1 stick.")